var data = [
	{"answer":"12 Years A Slave","question":"In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery."},
	{"answer":"The Sound of Music","question":"A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower."},
	{"answer":"The Sting","question":"In Chicago in September 1936, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker."},
	{"answer":"Gladiator","question":"When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge."},
	{"answer":"Grand Hotel","question":"A group of very different individuals staying at a luxurious hotel in Berlin deal with each of their respective dramas."},
	{"answer":"All About Eve","question":"An ingenue insinuates herself in to the company of an established but aging stage actress and her circle of theater friends."},
	{"answer":"It Happened One Night","question":"A spoiled heiress, running away from her family, is helped by a man who is actually a reporter in need of a story."},
	{"answer":"Titanic","question":"A seventeen-year-old aristocrat falls in love with a kind, but poor artist aboard an ill-fated vehicle"},
	{"answer":"Birdman or (The Unexpected Virtue of Ignorance)","question":"Illustrated upon the progress of his latest Broadway play, a former popular actor's struggle to cope with his current life as a wasted actor is shown."},
	{"answer":"Braveheart","question":"When his secret bride is executed for assaulting an English soldier who tried to rape her, a knight begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist."},
	{"answer":"The Deer Hunter","question":"An in-depth examination of the ways in which the U.S. Vietnam war impacts and disrupts the lives of people in a small industrial town in Pennsylvania."},
	{"answer":"Mutiny on the Bounty","question":"A sailor successfully leads a revolt against his ruthless ship captain. The captain returns one year later, hell bent on avenging his captors."},
	{"answer":"Kramer vs. Kramer","question":"A man rediscovers his bond with his son after his wife leaves him, but a custody battle over the child deepens the wounds left by separation"},
	{"answer":"The Great Ziegfeld","question":"The ups and downs of Florenz Ziegfeld, famed producer of extravagant stage revues."},
	{"answer":"Gandhi","question":"The life of the lawyer who became the famed leader of the Indian revolt against the British rule through his philosophy of nonviolent protest."},
	{"answer":"Midnight Cowboy","question":"A naive hustler goes to New York to seek personal fortune, but in the process finds himself a new friend."},
	{"answer":"Hamlet","question":"A Danish prince struggles over whether or not he should kill his uncle, whom he suspects has murdered his father, the former king."},
	{"answer":"How Green Was My Valley","question":"At the turn of the century in a Welsh mining village, a family raises coal-mining sons and hope their youngest will find a better life."},
	{"answer":"The Apartment","question":"A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue."},
	{"answer":"The Godfather Part II","question":"The early life and career of a gangster in 1920s New York is portrayed while his son expands and tightens his grip on his crime syndicate"},
	{"answer":"The Bridge on the River Kwai","question":"After settling his differences with a Japanese PoW camp commander, a British colonel co-operates to oversee his men's construction of a railway bridge for their captors - while oblivious to a plan by the Allies to destroy it."},
	{"answer":"In the Heat of the Night","question":"An African American police detective is asked to investigate a murder in a racially hostile southern town."},
	{"answer":"Going My Way","question":"A youthful Father who has led a colorful life of sports, song, and romance before joining the Roman Catholic clergy, is met with skepticism. But he inspires the youth of his parish and transform it completely"},
	{"answer":"American Beauty","question":"A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend."},
	{"answer":"Casablanca","question":"During the early days of World War II, an American expatriate meets a former lover, with unforeseen complications."},
	{"answer":"You Can't Take It with You","question":"A man from a family of rich snobs becomes engaged to a woman from a good-natured, but decidedly eccentric, family."},
	{"answer":"The Lord of the Rings: The Return of the King","question":"A wizard and a king lead an army against an evil lord's army to draw his gaze from the plot to destroy his source of power."},
	{"answer":"The Last Emperor","question":"The story of the final Emperor of China."},
	{"answer":"Lawrence of Arabia","question":"A brilliant, flamboyant, and controversial British military figure and his conflicted loyalties during wartime service."},
	{"answer":"The Godfather","question":"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."},
	{"answer":"West Side Story","question":"Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy."},
	{"answer":"The Artist","question":"A silent movie star meets a young dancer, but the arrival of talking pictures sends their careers in opposite directions."},
	{"answer":"The English Patient","question":"At the close of WWII, a young nurse tends to a badly-burned plane crash victim. His past is shown in flashbacks, revealing an involvement in a fateful love affair."},
	{"answer":"Rocky","question":"A small-time boxer gets a supremely rare chance to fight the heavy-weight champion in a bout in which he strives to go the distance for his self-respect."},
	{"answer":"Annie Hall","question":"A neurotic New York comedian falls in love with a ditsy girl."},
	{"answer":"Gone with the Wind","question":"A manipulative Southern belle carries on a turbulent affair with a blockade runner during the American Civil War."},
	{"answer":"Rebecca","question":"A self-conscious bride is tormented by the memory of her husband's dead first wife."},
	{"answer":"Chariots of Fire","question":"Two British track athletes, one a determined Jew and the other a devout Christian, compete in the 1924 Olympics."},
	{"answer":"Gentleman's Agreement","question":"A reporter pretends to be Jewish in order to cover a story on anti-Semitism, and personally discovers the true depths of bigotry and hatred."},
	{"answer":"Around the World in 80 Days","question":"A Victorian Englishman who bets that with the new steamships and railways he can help him win a bet"},
	{"answer":"Mrs. Miniver","question":"A British family struggles to survive the first months of World War II."},
	{"answer":"On the Waterfront","question":"An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses."},
	{"answer":"Dances With Wolves","question":"Exiled to a remote western Civil War outpost, a lieutenant befriends wolves and Indians, making him an intolerable aberration in the military."},
	{"answer":"Chicago","question":"Two murderesses find themselves on death row together and fight for the fame that will keep them from the gallows in 1920s Chicago."},
	{"answer":"The Silence of the Lambs","question":"A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer"},
	{"answer":"The Departed","question":"An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston."},
	{"answer":"Cavalcade","question":"A cavalcade of English life from New Year's Eve 1899 until 1933 seen through the eyes of well-to-do Londoners Jane and Robert Marryot"},
	{"answer":"Cimarron","question":"A newspaper editor settles in an Oklahoma boom town with his reluctant wife at the end of the nineteenth century."},
	{"answer":"Out of Africa","question":"In 20th-century colonial Kenya, a Danish baroness/plantation owner has a passionate love affair with a free-spirited big-game hunter."},
	{"answer":"The Hurt Locker","question":"During the Iraq War, a Sergeant recently assigned to an army bomb squad is put at odds with his squad mates due to his maverick way of handling his work."},
	{"answer":"Platoon","question":"A young recruit in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man."},
	{"answer":"Shakespeare in Love","question":"A young Shakespeare, out of ideas and short of cash, meets his ideal woman and is inspired to write one of his most famous plays."},
	{"answer":"SchindlerÍs List","question":"In Poland during World War II, a businessman gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis."},
	{"answer":"Terms of Endearment","question":"Follows hard-to-please Aurora looking for love and her daughter's family problems."},
	{"answer":"Patton","question":"The World War II phase of the career of a controversial American general"},
	{"answer":"The Best Years of Our Lives","question":"Three WWII veterans return home to small-town America to discover that they and their families have been irreparably changed."},
	{"answer":"Crash","question":"Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption."},
	{"answer":"All Quiet on the Western Front","question":"A young soldier faces profound disillusionment in the soul-destroying horror of World War I."},
	{"answer":"Ben-Hur","question":"When a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge."},
	{"answer":"Slumdog Millionaire","question":"A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of "},
	{"answer":"The King's Speech","question":"The story of King George VI of the United Kingdom of Great Britain and Northern Ireland, his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it."},
	{"answer":"Gigi","question":"Weary of the conventions of Parisian society, a rich playboy and a youthful courtesan-in-training enjoy a platonic friendship, but it may not stay platonic for long."},
	{"answer":"An American in Paris","question":"Three friends struggle to find work in Paris. However, things become more complicated when two of them fall in love with the same woman."},
	{"answer":"Driving Miss Daisy","question":"An old Jewish woman and her African-American chauffeur in the American South have a relationship that grows and improves over the years."},
	{"answer":"Million Dollar Baby","question":"A determined woman works with a hardened boxing trainer to become a professional."},
	{"answer":"Wings","question":"Two young men, one rich, one middle class, who are in love with the same woman, become fighter pilots in World War I."},
	{"answer":"Rain Man","question":"A selfish yuppie discovers his father has left a fortune to his savant brother and a pittance to him; the duo travel cross-country"},
	{"answer":"The French Connection","question":"A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection."},
	{"answer":"One Flew over the Cuckoo's Nest","question":"A criminal pleads insanity after getting into trouble again and once in the mental institution, rebels against the oppressive nurse and rallies up the scared patients."},
	{"answer":"Oliver!","question":"Musical adaptation about an orphan who runs away from an orphanage and hooks up with a group of boys trained to be pickpockets by an elderly mentor."},
	{"answer":"Marty","question":"A middle-aged butcher and a school teacher who have given up on the idea of love, meet at a dance and fall in love."},
	{"answer":"The Broadway Melody","question":"Harriet and Queenie Mahoney, a vaudeville act, come to Broadway, where their friend Eddie Kerns invites his girlfriend Hank to join him."},
	{"answer":"All the Kings Men","question":"The rise and fall of a corrupt politician, who makes his friends richer and retains power by dint of a populist appeal."},
	{"answer":"A Man for All Seasons","question":"The story of Thomas More, who stood up to King Henry VIII when the King rejected the Roman Catholic Church to obtain a divorce and remarriage."},
	{"answer":"The Lost Weekend","question":"The desperate life of a chronic alcoholic is followed through a four day drinking bout."},
	{"answer":"Tom Jones","question":"In eighteenth century England, "},
	{"answer":"From Here to Eternity","question":"In 1941 Hawaii, a private is cruelly punished for not boxing on his unit's team, while his captain's wife and second in command are falling in love."},
	{"answer":"Amadeus","question":"The incredible story of a legendary musician, told by his peer and secret rival - now confined to an insane asylum."},
	{"answer":"No Country for Old Men","question":"Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande."},
	{"answer":"The Greatest Show on Earth","question":"The dramatic lives of trapeze artists, a clown, and an elephant trainer against a background of circus spectacle."},
	{"answer":"Unforgiven","question":"A retired Old West gunslinger reluctantly takes on one last job, with the help of his old partner and a young man."},
	{"answer":"Forrest Gump","question":"A seemingly unintelligent man has accidentally been present at many historic moments, but his true love eludes him."},
	{"answer":"My Fair Lady","question":"A misogynistic and snobbish phonetics professor agrees to a wager that he can take a flower girl and make her presentable in high society."},
	{"answer":"A Beautiful Mind","question":"After a brilliant but asocial mathematician accepts secret work in cryptography, his life takes a turn for the nightmarish."},
	{"answer":"Argo","question":"Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980."},
	{"answer":"The Life of Emile Zola","question":"The biopic of the famous French muckraking writer and his involvement in fighting the injustice of the Dreyfuss Affair."},
	{"answer":"Ordinary People","question":"The accidental death of the older son of an affluent family deeply strains the relationships among the bitter mother, the good-natured father, and the guilt-ridden younger son."}
];

var scoreGifs = [
];